In [2]:
import numpy as np
from sklearn import linear_model
import pandas as pd

In [5]:
df=pd.read_csv("homeprices.csv")
df.head(6)

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
df.isna().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [14]:
df.bedrooms=df.bedrooms.fillna(df.bedrooms.median())

In [15]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [17]:
reg=linear_model.LinearRegression()

reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [18]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [19]:
 reg.intercept_

221323.00186540396

In [22]:
reg.predict([[2500,4,5]])

/Users/shashank.gupta/test/lib/python3.9/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])

In [23]:
k2=pd.read_csv("hiring.csv")

In [38]:
k2["test_score(out of 10)"]=k2["test_score(out of 10)"].fillna(k2["test_score(out of 10)"].median())

In [26]:
from word2number import w2n

In [41]:
k2.experience=k2.experience.fillna("zero")

In [55]:
k2.experience=k2.experience.apply(w2n.word_to_num)

ValueError: Type of input is not string! Please enter a valid number word (eg. 'two million twenty three thousand and forty nine')

In [43]:
k2.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [49]:
reg=linear_model.LinearRegression()

In [52]:
reg.fit(k2[["experience","test_score(out of 10)","interview_score(out of 10)"]],k2["salary($)"])

LinearRegression()

In [54]:
reg.predict([[12,10,10]])

/Users/shashank.gupta/test/lib/python3.9/site-packages/sklearn/base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])